version: '3'
services:
  ngapp:
    build:
      context: ./ng-app
    hostname: ng.dev
    ports:
      - "7000:80"
    networks:
      dcc-net:
        aliases:
          - ng.dev

  apiapp:
    build:
      context: ./api-app
    hostname: api.dev
    ports:
      - "3333:3333"
    networks:
      dcc-net:
        aliases:
          - api.dev

networks:
  dcc-net: