version: '3'
services:
  ngapp:
    image: siata/ng-app
    hostname: ng.dev
    ports:
      - "7000:80"
    networks:
      dc-net:
        aliases:
          - ng.dev
    depends_on:
      - apiapp

  apiapp:
    image: siata/api-app
    hostname: api.dev
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGO_HOST=mongodb://localhost:27017/mydatabase
    networks:
      dc-net:
        aliases:
          - api.dev
    depends_on:
      - mongodb
      
   mongo:
    image: mongo:latest
    hostname: mongo.dev
    ports:
      - "27019:27017"
    networks:
      dc-net:
        aliases:
          - mongo.dev
    depends_on:
      - mongodb     

networks:
  dc-net: