version: '3'
services:
  ngapp:
    image: siata/ng-app
    hostname: ng.dev
    ports:
      - "7000:80"
    networks:
      dc-net:
        aliases:
          - ng.dev

  apiapp:
    image: siata/api-app
    hostname: api.dev
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGO_HOST=mongodb://mongo.dev:27017/
      - MONGO_DB_NAME=mydatabase
    networks:
      dc-net:
        aliases:
          - api.dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    hostname: mongo.dev
    ports:
      - "27019:27017"
    networks:
      dc-net:
        aliases:
          - mongo.dev

networks:
  dc-net: