version: '3'
services:
  ngapp:
    image: siata/ng-app
    hostname: ng.dev
    ports:
      - "7000:80"
    networks:
      dc-net:
        aliases:
          - ng.dev

  apiapp:
    image: siata/api-app
    hostname: api.dev
    ports:
      - "3333:3333"
    networks:
      dc-net:
        aliases:
          - api.dev

networks:
  dc-net: